### ISSUE TITLE
Only working for some values

### ISSUE THREAD

**Issue by wplatzer** [2bbb/ofxHammingCode#1]
Hello,

I tried testH3126SECDED() with Visual Studio 2015.
For d = 16972 it is working fine. But for many other values it is not working.
E.g. for d =99 isCorrect() returns false.

Did you check this code with different values?

best regards,
Wolfgang

**Comment by 2bbb** [comment]
@wplatzer 

oh my god.
exactly, you're right.

i will fix it. (but i forgot some part of calculation...)

thanks!!

**Comment by 2bbb** [comment]
@wplatzer 

maybe currently master was fixed!
please check it!!

thanks!

**Comment by wplatzer** [comment]
Hi,

now it works fine. I already made the same changes and tested with all possible values.

br,
Wolfgang

**Comment by 2bbb** [comment]
@wplatzer 

thanks for checking!
